---
title: "Présentation des données - Rapport court intermédiaire"
subtitle: "ERIE - An 2"
author: "Nicolas Bressoud"
date: "`r format(Sys.time(), '%d.%m.%Y')`"
toc-title: "Table des matières"
output:
  officedown::rdocx_document:
    reference_docx: "template2.docx"
    toc: true
    toc_depth: 1
params:
  save: false # génère des xlsx des données pour sauvegarde si true
  cua: 198632 # code survey cua
  url_survey: "https://sondage.competences-emotionnelles.ch/admin/remotecontrol"
  login_survey: nbr_low
  pass_survey: 82BBdJyTjqzz
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(tidyverse)
library(lubridate)
library(rio)
library(readxl)
library(ggrepel) # pour les labels des plots
library(limer)

# Acquisition des données

options(lime_api = params$url_survey)
options(lime_username = params$login_survey)
options(lime_password = params$pass_survey)

# log in
get_session_key()

# data

responses <- get_responses(params$cua, sResponseType = "short")  
peers <- responses

#log out
release_session_key()


```


# Description du projet

origine, visées

# Contexte et organisation

## Auteurs

## Méthodologie

## Echelles

# Données

description de la méthode de traitement.

<!-- tu peux faire ton clean data dans le chunk ci-dessous. -->

```{r clean}

```

## Echantillon et description

<!-- A partir d'ici, on génère des sorties "propres". -->


```{r sample}

```

## Agrégation

### tableaux

```{r table1}

```

### plots

```{r plot1}

```

